services:
  db:
    image: mariadb:12
    container_name: gremio_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 190326
      MARIADB_DATABASE: gremio_estudantil
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/backup.sql:/docker-entrypoint-initdb.d/backup.sql

  backend:
    build: ./backend
    container_name: gremio_api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 190326
      DB_NAME: gremio_estudantil
    volumes:
      - ./backend:/app

volumes:
  db_data: